# Generated by Django 6.0.8 on 2026-09-23 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resalesnapshot',
            options={'ordering': ['-snapshot_date', '-observed_at'], 'verbose_name': '리셀 스냅샷', 'verbose_name_plural': '리셀 스냅샷'},
        ),
        migrations.RemoveConstraint(
            model_name='resalesnapshot',
            name='uq_resale_snap',
        ),
        migrations.RemoveIndex(
            model_name='resalesnapshot',
            name='idx_resale_index',
        ),
        migrations.RemoveIndex(
            model_name='resalesnapshot',
            name='idx_resale_prod',
        ),
        migrations.AddField(
            model_name='resalesnapshot',
            name='snapshot_date',
            field=models.DateField(blank=True, db_index=True, help_text='한국 시간 기준 수집 날짜', null=True, verbose_name='스냅샷 기준일'),
        ),
        migrations.AlterField(
            model_name='resalesnapshot',
            name='highest_bid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='최고 구매 호가'),
        ),
        migrations.AlterField(
            model_name='resalesnapshot',
            name='lowest_ask',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='최저 판매 호가'),
        ),
        migrations.AlterField(
            model_name='resalesnapshot',
            name='market_metrics',
            field=models.JSONField(blank=True, default=dict, help_text='사이즈별 가격 요약, 표본 통계, 수집 범위 및 플랫폼별 추가 시장 지표', verbose_name='추가 시장 지표'),
        ),
        migrations.AlterField(
            model_name='resalesnapshot',
            name='observed_at',
            field=models.DateTimeField(db_index=True, help_text='해당 날짜에 마지막으로 수집된 데이터의 관측 시각', verbose_name='최종 관측일시'),
        ),
        migrations.AlterField(
            model_name='resalesnapshot',
            name='resale_index',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='FEEDIT 분석 파이프라인에서 산출하는 지표', max_digits=10, null=True, verbose_name='리셀 지수'),
        ),
        migrations.AlterField(
            model_name='resalesnapshot',
            name='resale_price_ratio',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='최근 거래가 / 검증된 발매가', max_digits=10, null=True, verbose_name='리셀 가격 비율'),
        ),
        migrations.AddIndex(
            model_name='resalesnapshot',
            index=models.Index(fields=['-snapshot_date', '-resale_index'], name='idx_resale_date_index'),
        ),
        migrations.AddIndex(
            model_name='resalesnapshot',
            index=models.Index(fields=['product_source', '-snapshot_date'], name='idx_resale_prod_date'),
        ),
        migrations.AddConstraint(
            model_name='resalesnapshot',
            constraint=models.UniqueConstraint(fields=('product_source', 'snapshot_date'), name='uq_resale_daily'),
        ),
    ]
