# Generated by Django 6.0.8 on 2026-09-28 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_resalesnapshot_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productsourcesnapshot',
            options={'ordering': ['-snapshot_date', '-observed_at'], 'verbose_name': '상품 스냅샷', 'verbose_name_plural': '상품 스냅샷'},
        ),
        migrations.RemoveConstraint(
            model_name='productsourcesnapshot',
            name='uq_prod_snapshot_scope',
        ),
        migrations.RemoveIndex(
            model_name='productsourcesnapshot',
            name='idx_prod_snap_time',
        ),
        migrations.RemoveIndex(
            model_name='productsourcesnapshot',
            name='idx_prod_snap_prod_time',
        ),
        migrations.AddField(
            model_name='productsourcesnapshot',
            name='snapshot_date',
            field=models.DateField(blank=True, db_index=True, help_text='한국 시간 기준 수집 날짜', null=True, verbose_name='스냅샷 기준일'),
        ),
        migrations.AlterField(
            model_name='productsourcesnapshot',
            name='observed_at',
            field=models.DateTimeField(db_index=True, help_text='해당 날짜에 마지막으로 수집된 데이터의 관측 시각', verbose_name='최종 관측일시'),
        ),
        migrations.AddIndex(
            model_name='productsourcesnapshot',
            index=models.Index(fields=['-snapshot_date', '-observed_at'], name='idx_prod_snap_date'),
        ),
        migrations.AddIndex(
            model_name='productsourcesnapshot',
            index=models.Index(fields=['product_source', '-snapshot_date'], name='idx_prod_snap_prod_date'),
        ),
        migrations.AddConstraint(
            model_name='productsourcesnapshot',
            constraint=models.UniqueConstraint(fields=('product_source', 'snapshot_date', 'ranking_scope'), name='uq_prod_snapshot_daily_scope'),
        ),
    ]
