# Generated by Django 6.0.8 on 2026-09-28 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_productsourcesnapshot_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productterm',
            options={'verbose_name': '상품 특성 관계', 'verbose_name_plural': '상품 특성 관계'},
        ),
        migrations.RemoveConstraint(
            model_name='productterm',
            name='uq_prodsrc_term',
        ),
        migrations.AddField(
            model_name='productterm',
            name='relation_type',
            field=models.CharField(blank=True, choices=[('HAS_ITEM', '아이템'), ('HAS_MATERIAL', '소재'), ('HAS_COLOR', '색상'), ('HAS_FIT', '핏'), ('HAS_SILHOUETTE', '실루엣'), ('HAS_NECKLINE', '넥라인'), ('HAS_SLEEVE', '소매'), ('HAS_LENGTH', '기장'), ('HAS_SHAPE', '형태'), ('HAS_DETAIL', '디테일'), ('HAS_STYLE', '스타일'), ('HAS_TPO', 'TPO')], db_index=True, max_length=32, null=True, verbose_name='관계 유형'),
        ),
        migrations.AddIndex(
            model_name='productterm',
            index=models.Index(fields=['relation_type', 'term'], name='idx_prod_term_relation'),
        ),
        migrations.AddConstraint(
            model_name='productterm',
            constraint=models.UniqueConstraint(fields=('product_source', 'term', 'relation_type'), name='uq_prodsrc_term_relation'),
        ),
    ]
