# Generated by Django 6.0.8 on 2026-09-28 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_productterm_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productterm',
            name='relation_type',
            field=models.CharField(choices=[('HAS_ITEM', '아이템'), ('HAS_MATERIAL', '소재'), ('HAS_COLOR', '색상'), ('HAS_FIT', '핏'), ('HAS_SILHOUETTE', '실루엣'), ('HAS_NECKLINE', '넥라인'), ('HAS_SLEEVE', '소매'), ('HAS_LENGTH', '기장'), ('HAS_SHAPE', '형태'), ('HAS_DETAIL', '디테일'), ('HAS_STYLE', '스타일'), ('HAS_TPO', 'TPO')], db_index=True, max_length=32, verbose_name='관계 유형'),
        ),
    ]
